name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]  # Parallelizing across different browsers
        playwright-version: [1.44.0]     # Choose a specific version or latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # your .NET version

    # Step 3: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Step 4: Install dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 5: Build the project
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # Step 6: Run Playwright Tests
    - name: Run Playwright Tests
      run: dotnet test --filter FullyQualifiedName~PlaywrightTests --configuration Release --no-build --verbosity normal
      env:
        BROWSER: ${{ matrix.browser }}
        
    # Step 7: Upload Test Results (Optional)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.browser }}
        path: TestResults/${{ matrix.browser }}
