name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]  # Parallelizing across different browsers
        playwright-version: [1.44.0] 

    steps:

    # Step 1: Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up .NET
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # your .NET version

    # Step 3: Build & Install   
    - name: Build & Install
      run: dotnet build

    # Step 3: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Step 4: Install dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 5: Build the project
    - name: Build the project
      run: dotnet build --configuration Release --no-restore --verbosity detailed

    # Step 6: Run Playwright Tests
    - name: Run Playwright Tests
      run: dotnet test TechTaskVeli.Tests/TechTaskVeli.Tests.csproj --configuration Release --no-build --verbosity normal
      env:
        BROWSER: ${{ matrix.browser }}
    
    # Step 7: Load test report history
    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # Step 8: Build test report
    - name: Build test report
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    # Step 9: Publish test report
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
